project:
  type: book
execute:
  freeze: auto
resources:
    - images/
    - figures/
book:
  title: "Code Resources for MEC-24-1288"
  author: ""
  date: "1/10/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Building global BOLD data"
      chapters:    
      - building_bold.qmd
    - part: "Geographic coverage"
      chapters:
      - geocov_figs1.qmd
      - geocov_figs2.qmd
    - part: "Taxonomic coverage"
      chapters:
      - fetch_itis.qmd
      - taxonomic_coverage.qmd
    - part: "Case-study -- Yellowstone"
      chapters:
      - geocov_ynp_selected.qmd
      - fetch_gbif.qmd
      - build_geocov_map.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: false

editor: visual

