# Introduction {.unnumbered}

This codebook is divided into four parts that follow the Methods section of the manuscript and includes eight code notebooks that were used in the analyses for this publication.

Source code is available in a GitHub [repository](https://github.com/trklab-metabarcoding/MolEco-MEC-1288)

Supplementary data sets (S1-S4) can be downloaded from the supplement available with the published paper. Move those four files into the `/data` folder in the GitHub repository when running the code notebooks.

If running notebooks from the repository, headers in the data retrieved may differ than headers in the datasets provided in the Supplemental Materials.

<br>

### Building global BOLD data

1.  [Building the BOLD dataset](building_bold.qmd)

### Geographic coverage

2.  [Coverage by climatic zones](geocov_figs1.qmd)
3.  [Coverage by country](geocov_figs2.qmd)

### Taxonomic coverage

4.  [Fetching data from ITIS](fetch_itis.qmd)
5.  [Correlations -- plant species and available barcodes](taxonomic_coverage.qmd)

### Case-study Yellowstone National Park

6.  [Continent-scale barcode coverage of lodgepole pine and big sagebrush](geocov_ynp_selected.qmd)
7.  [Fetching data from GBIF](fetch_gbif.qmd)
8.  [Case-study in geographic coverage of site-based reference data](build_geocov_map.qmd)
